import type { WorkflowDefinition } from "../types.js";

export const courtWorkflow: WorkflowDefinition = {
  id: "court",
  name: "Court Mode",
  purpose: "Structured multi-role adversarial debate that stress-tests a product idea from market, distribution, product, technical, business, and user perspectives, then produces a balanced verdict with next actions.",
  whenToUse: "The idea is important enough for deeper critique — court surfaces hidden assumptions and weak points across multiple dimensions.",
  inputGuidance: [
    "A clear description of the product idea",
    "Target user segments (optional)",
    "Market context (optional)",
    "Idea stage: napkin / pre-mvp / mvp / growth (optional)",
  ],
  roles: [
    {
      id: "market-skeptic",
      name: "Market Skeptic",
      stance: "skeptic",
      mandate: "Attacks demand, urgency, willingness to pay, market size, and timing assumptions.",
      mustAddress: [
        "Is there genuine demand or just founder enthusiasm?",
        "Is the timing right for this solution?",
        "What would willingness to pay actually be?",
        "Is the addressable market large enough?",
        "What market trends could kill this idea?",
      ],
    },
    {
      id: "distribution-skeptic",
      name: "Distribution Skeptic",
      stance: "skeptic",
      mandate: "Attacks acquisition channels, CAC, virality assumptions, SEO/content/platform risk, and sales motion.",
      mustAddress: [
        "How would users realistically discover this?",
        "What is a realistic CAC for each channel?",
        "Does the idea rely on viral growth that won't happen?",
        "What platform dependency risks exist?",
        "What is the sales motion and why would it work?",
      ],
    },
    {
      id: "product-skeptic",
      name: "Product Skeptic",
      stance: "skeptic",
      mandate: "Attacks UX complexity, retention, habit formation, onboarding friction, and edge cases.",
      mustAddress: [
        "What is the activation experience and why would users complete it?",
        "What is the retention loop and does it exist?",
        "What edge cases could break the core experience?",
        "How much behavior change is required?",
        "What happens when the experience fails or delivers low quality?",
      ],
    },
    {
      id: "technical-skeptic",
      name: "Technical Skeptic",
      stance: "skeptic",
      mandate: "Attacks implementation complexity, reliability requirements, integration dependencies, scalability needs, and operational burden.",
      mustAddress: [
        "What is the hardest technical problem to solve?",
        "What third-party dependencies exist and what happens if they break?",
        "What scale challenges would emerge if it works?",
        "What operational burden does a small team face?",
        "What integration complexity could delay launch?",
      ],
    },
    {
      id: "business-defender",
      name: "Business Defender",
      stance: "defender",
      mandate: "Argues the strongest credible wedge, customer segment, pricing, GTM path, and differentiation.",
      mustAddress: [
        "What is the most defensible wedge into the market?",
        "Which customer segment is most likely to adopt first?",
        "What pricing model aligns with value delivered?",
        "What is the most credible GTM path?",
        "What genuine differentiation exists?",
      ],
    },
    {
      id: "user-advocate",
      name: "User Advocate",
      stance: "user",
      mandate: "Argues from the target user's perspective: jobs-to-be-done, anxieties, switching costs, and realistic alternatives.",
      mustAddress: [
        "What job is the user really hiring this for?",
        "What anxiety or risk does the user feel about adopting?",
        "What is the user's current workaround and why is it acceptable?",
        "What switching costs exist (data, habit, social)?",
        "What would need to be true for the user to recommend this?",
      ],
    },
    {
      id: "judge",
      name: "Judge",
      stance: "judge",
      mandate: "Weighs all arguments, separates evidence from assumptions, identifies decisive unknowns, produces verdict and recommended next tests.",
      mustAddress: [
        "Which arguments have the strongest evidence?",
        "What is assumed vs known vs unknowable right now?",
        "What single test would resolve the most important uncertainty?",
        "What is the verdict and confidence level?",
        "What should the founder do next?",
      ],
    },
  ],
  phases: [
    {
      id: "idea-snapshot",
      name: "Idea Snapshot",
      participants: ["judge"],
      instruction: "Summarize the idea, target user, market, stage, and key promise in 3-5 sentences.",
    },
    {
      id: "assumptions-map",
      name: "Assumptions Map",
      participants: ["judge"],
      instruction: "List the top 5-10 assumptions the idea depends on, ranked by how risky they are if wrong.",
    },
    {
      id: "opening-statements",
      name: "Opening Statements",
      participants: [
        "market-skeptic",
        "distribution-skeptic",
        "product-skeptic",
        "technical-skeptic",
        "business-defender",
        "user-advocate",
      ],
      instruction: "Each role provides one concise paragraph stating their strongest case.",
    },
    {
      id: "skeptic-cases",
      name: "Specialist Skeptic Cases",
      participants: [
        "market-skeptic",
        "distribution-skeptic",
        "product-skeptic",
        "technical-skeptic",
      ],
      instruction: "Each skeptic delivers specific, testable objections with concrete reasoning. Include at least one 'kill test' per skeptic — a test that, if it fails, should kill the idea.",
    },
    {
      id: "defender-response",
      name: "Defender Response",
      participants: ["business-defender"],
      instruction: "Respond to the skeptics' strongest points. Identify where they are wrong, overstated, or missing context. Concede valid points honestly.",
    },
    {
      id: "user-advocate-response",
      name: "User Advocate Response",
      participants: ["user-advocate"],
      instruction: "Challenge both skeptics and defender from the real user's perspective. Identify arguments that sound compelling in theory but wouldn't survive contact with actual users.",
    },
    {
      id: "cross-examination",
      name: "Cross-Examination",
      participants: ["judge"],
      instruction: "Synthesize the key exchanges. Identify where roles disagree most sharply. Flag assumptions that multiple roles treated as fact but are actually untested.",
    },
    {
      id: "evidence-audit",
      name: "Evidence Audit",
      participants: ["judge"],
      instruction: "Categorize every major claim as: (a) supported by evidence, (b) reasonable assumption, (c) unknown and testable, or (d) speculative. Be honest about what is not known.",
    },
    {
      id: "kill-tests",
      name: "Kill Tests",
      participants: ["judge"],
      instruction: "Propose 3-5 specific tests that would validate or invalidate the idea. Each test must have a clear method, timeline, success signal, and kill signal.",
    },
    {
      id: "scoring",
      name: "Scoring",
      participants: ["judge"],
      instruction: "Score each dimension 0-10. Provide a brief reason for each score.",
    },
    {
      id: "verdict",
      name: "Judge Verdict",
      participants: ["judge"],
      instruction: "Deliver the final verdict with confidence level and the single most important reason for the decision.",
    },
    {
      id: "next-actions",
      name: "Next Actions",
      participants: ["judge"],
      instruction: "List 3-5 concrete next actions ranked by importance. Each action should specify what to do and what signal would indicate whether to proceed or pivot.",
    },
  ],
  sections: [
    {
      id: "idea-snapshot",
      heading: "Idea Snapshot",
      purpose: "Brief summary of the idea being evaluated",
      required: ["Idea", "Target user", "Market", "Stage", "Key promise"],
    },
    {
      id: "assumptions-map",
      heading: "Assumptions Map",
      purpose: "Key assumptions ranked by risk",
      required: ["Assumption list with risk ranking"],
    },
    {
      id: "market-skeptic-case",
      heading: "Market Skeptic Case",
      purpose: "Market-focused critique",
      required: ["Demand critique", "Urgency assessment", "Willingness to pay", "Market size", "Timing"],
    },
    {
      id: "distribution-skeptic-case",
      heading: "Distribution Skeptic Case",
      purpose: "Distribution-focused critique",
      required: ["Channel analysis", "CAC estimate", "Virality critique", "Platform risk", "Sales motion"],
    },
    {
      id: "product-skeptic-case",
      heading: "Product Skeptic Case",
      purpose: "Product-focused critique",
      required: ["Activation", "Retention loop", "Edge cases", "Behavior change", "Failure modes"],
    },
    {
      id: "technical-skeptic-case",
      heading: "Technical Skeptic Case",
      purpose: "Technical critique",
      required: ["Hardest tech problem", "Dependencies", "Scale challenges", "Operational burden"],
    },
    {
      id: "business-defender-case",
      heading: "Business Defender Case",
      purpose: "Defense of the idea",
      required: ["Best wedge", "Target segment", "Pricing", "GTM path", "Differentiation"],
    },
    {
      id: "user-advocate-case",
      heading: "User Advocate Case",
      purpose: "User-centered challenge",
      required: ["Jobs-to-be-done", "Anxieties", "Switching costs", "Alternatives"],
    },
    {
      id: "cross-examination",
      heading: "Cross-Examination",
      purpose: "Synthesis of key exchanges and disagreements",
      required: ["Key exchanges", "Sharpest disagreements", "Untested assumptions"],
    },
    {
      id: "evidence-audit",
      heading: "Evidence Audit",
      purpose: "Categorize claims by evidence level",
      required: ["Evidence-backed claims", "Reasonable assumptions", "Unknown/testable", "Speculative"],
    },
    {
      id: "kill-tests",
      heading: "Kill Tests",
      purpose: "Specific tests that could invalidate the idea",
      required: ["3-5 tests with method, timeline, success signal, kill signal"],
    },
    {
      id: "scoring",
      heading: "Scores",
      purpose: "Diagnostic scoring with reasons",
      required: ["Scores 0-10 per dimension with reasons"],
    },
    {
      id: "verdict",
      heading: "Verdict",
      purpose: "Final decision with confidence",
      required: ["Decision", "Confidence", "Main reason"],
    },
    {
      id: "next-actions",
      heading: "Next Actions",
      purpose: "Actionable next steps",
      required: ["3-5 ranked actions with success signals"],
    },
  ],
  scoringDimensions: [
    { id: "clarity", label: "Clarity", definition: "Is the idea specific and understandable? Can you explain it in one sentence?" },
    { id: "pain", label: "Pain", definition: "Is there a real painful problem that users actively try to solve?" },
    { id: "urgency", label: "Urgency", definition: "Do users need this now, or is it a 'nice to have' that gets deprioritized?" },
    { id: "differentiation", label: "Differentiation", definition: "Is the approach meaningfully different from existing alternatives?" },
    { id: "distribution", label: "Distribution", definition: "Can the product reach its target users at a reasonable cost?" },
    { id: "monetization", label: "Monetization", definition: "Is there a credible path to revenue that users will accept?" },
    { id: "buildability", label: "Buildability", definition: "Can a small team build and test this quickly?" },
    { id: "retention", label: "Retention", definition: "Will users return regularly or churn after novelty fades?" },
    { id: "evidence", label: "Evidence", definition: "What real evidence supports the idea beyond founder belief?" },
    { id: "overall", label: "Overall", definition: "Combined assessment — not an average of other scores." },
  ],
  outputRules: [
    "Provide evidence-aware analysis — clearly label what is known vs assumed",
    "Be specific and concrete, not generic startup advice",
    "Do not predict success — identify decisive tests instead",
    "Every score must include a reason",
    "Kill tests must have falsifiable signals",
  ],
  requiredHeadings: [
    "Idea Snapshot",
    "Assumptions Map",
    "Market Skeptic Case",
    "Distribution Skeptic Case",
    "Product Skeptic Case",
    "Technical Skeptic Case",
    "Business Defender Case",
    "User Advocate Case",
    "Cross-Examination",
    "Evidence Audit",
    "Kill Tests",
    "Scores",
    "Verdict",
    "Next Actions",
  ],
};
