import type { WorkflowDefinition } from "../types.js";

export const mvpWorkflow: WorkflowDefinition = {
  id: "mvp",
  name: "MVP Planner",
  purpose: "Turn critique into an aggressive, minimal validation plan. Be ruthless about scope — the goal is to test the riskiest assumption as fast as possible.",
  whenToUse: "You want to stop debating and start testing the idea with real users.",
  inputGuidance: [
    "A clear description of the product idea",
    "The riskiest assumption to test (if known)",
    "Available resources and timeline constraints (optional)",
  ],
  roles: [
    {
      id: "planner",
      name: "MVP Planner",
      stance: "planner",
      mandate: "Design the fastest, cheapest test of the riskiest assumption. Ruthlessly exclude everything that does not directly test that assumption.",
      mustAddress: [
        "What is the single riskiest assumption?",
        "What is the fastest way to test it?",
        "What can be excluded from this test?",
        "What would constitute a pass vs fail?",
      ],
    },
  ],
  sections: [
    {
      id: "core-hypothesis",
      heading: "Core Hypothesis",
      purpose: "The falsifiable hypothesis the MVP will test",
      required: ["Hypothesis statement"],
    },
    {
      id: "riskiest-assumptions",
      heading: "Riskiest Assumptions",
      purpose: "Assumptions ranked by risk level",
      required: ["Assumption list with risk ranking"],
    },
    {
      id: "non-goals",
      heading: "What Not to Build Yet",
      purpose: "Features explicitly excluded from this MVP",
      required: ["Excluded features list"],
    },
    {
      id: "mvp-wedge",
      heading: "MVP Wedge",
      purpose: "The narrowest version that tests the hypothesis",
      required: ["MVP description", "Core feature set"],
    },
    {
      id: "validation-plan",
      heading: "14-Day Validation Plan",
      purpose: "Day-by-day plan for testing",
      required: ["Timeline", "Daily/weekly milestones"],
    },
    {
      id: "experiment-backlog",
      heading: "Experiment Backlog",
      purpose: "Additional experiments ranked by priority",
      required: ["Experiment descriptions with priority"],
    },
    {
      id: "fake-door-test",
      heading: "Landing Page / Fake-Door Test",
      purpose: "Design of the first signal-gathering experiment",
      required: ["Test design", "Expected conversion", "Duration"],
    },
    {
      id: "concierge-test",
      heading: "Concierge Test",
      purpose: "Manual service that simulates the product experience",
      required: ["Concierge process description"],
    },
    {
      id: "interview-script",
      heading: "Interview Script",
      purpose: "Questions to ask real potential users",
      required: ["5-10 interview questions"],
    },
    {
      id: "success-metrics",
      heading: "Success Metrics",
      purpose: "Quantifiable signals that validate the hypothesis",
      required: ["Metric definitions", "Target values"],
    },
    {
      id: "kill-criteria",
      heading: "Kill Criteria",
      purpose: "Conditions that indicate the idea should be abandoned or pivoted",
      required: ["Falsifiable kill signals"],
    },
    {
      id: "competitive-wedge",
      heading: "Competitive Wedge",
      purpose: "Based on competitor analysis, what wedge gives the best chance?",
      required: ["Competitor summary", "Chosen wedge", "Why this wedge works"],
    },
    {
      id: "niche-strategy",
      heading: "Niche Strategy",
      purpose: "Specific niche to target first",
      required: ["Target niche", "Why underserved", "How to reach them"],
    },
    {
      id: "pivot-options",
      heading: "Pivot Options",
      purpose: "Adjacent directions if the core hypothesis fails",
      required: ["2-3 pivot directions"],
    },
    {
      id: "recommended-scope",
      heading: "Recommended Scope",
      purpose: "Recommended build scope for the MVP",
      required: ["Build scope", "Timeline", "Team size"],
    },
  ],
  scoringDimensions: [],
  outputRules: [
    "Be ruthless about scope — if it doesn't test the riskiest assumption, exclude it",
    "Do not include auth, payments, or complex onboarding in a 14-day plan",
    "Every metric must have a concrete target (e.g., '40% session completion', not 'good engagement')",
    "Kill criteria must be specific and measurable",
    "Pivot options should be genuinely different, not minor variations",
    "The MVP wedge MUST be informed by competitor analysis — don't build what already exists",
    "If competitors exist, the MVP must target a specific gap or underserved segment",
    "Cite competitors by name when explaining the competitive wedge",
  ],
  requiredHeadings: [
    "Core Hypothesis",
    "Riskiest Assumptions",
    "What Not to Build Yet",
    "MVP Wedge",
    "14-Day Validation Plan",
    "Experiment Backlog",
    "Landing Page / Fake-Door Test",
    "Concierge Test",
    "Interview Script",
    "Success Metrics",
    "Kill Criteria",
    "Competitive Wedge",
    "Niche Strategy",
    "Pivot Options",
    "Recommended Scope",
  ],
};
