import { describe, it, expect } from "vitest";
import { runImmuneEngine } from "../../src/engines/immuneEngine.js";
import { runCourtEngine } from "../../src/engines/courtEngine.js";
import { runMvpPlanner } from "../../src/engines/mvpPlanner.js";
import { runUserLab } from "../../src/engines/syntheticUserLab.js";
import { runCompareEngine } from "../../src/engines/compareEngine.js";
import { extractJSON, stripMarkdownFences } from "../../src/utils/jsonRepair.js";
import type { LLMProvider, CompletionOptions } from "../../src/core/types.js";

/**
 * Provider that always throws — simulates network error / API failure.
 */
class ErrorProvider implements LLMProvider {
  kind = "custom" as const;
  async complete(): Promise<string> {
    throw new Error("Simulated network error");
  }
}

/**
 * Provider that returns empty string — simulates empty LLM response.
 */
class EmptyProvider implements LLMProvider {
  kind = "custom" as const;
  async complete(): Promise<string> {
    return "";
  }
}

/**
 * Provider that returns malformed JSON — simulates LLM returning prose.
 */
class MalformedProvider implements LLMProvider {
  kind = "custom" as const;
  async complete(): Promise<string> {
    return "Sorry, I cannot analyze this idea because I need more information.";
  }
}

/**
 * Provider that returns JSON wrapped in markdown fences.
 */
class FencedJsonProvider implements LLMProvider {
  kind = "custom" as const;
  async complete(): Promise<string> {
    return "```json\n{\"oneLineVerdict\": \"Test verdict\", \"topRisks\": [], \"topAssumptions\": [], \"bestCase\": \"\", \"worstCase\": \"\", \"distributionRisk\": \"\", \"monetizationRisk\": \"\", \"buildabilityRisk\": \"\", \"fastestValidationTest\": {\"description\": \"\", \"method\": \"\", \"timeline\": \"\", \"successSignal\": \"\"}, \"scores\": {\"clarity\": 5, \"pain\": 5, \"differentiation\": 5, \"buildability\": 5, \"distribution\": 5, \"monetization\": 5, \"evidence\": 3}, \"nextStep\": \"Test next step\"}\n```";
  }
}

/**
 * Provider that returns JSON with trailing text after the closing brace.
 */
class TrailingTextProvider implements LLMProvider {
  kind = "custom" as const;
  async complete(): Promise<string> {
    return '{"oneLineVerdict": "Trailing text test", "topRisks": [], "topAssumptions": [], "bestCase": "", "worstCase": "", "distributionRisk": "", "monetizationRisk": "", "buildabilityRisk": "", "fastestValidationTest": {"description": "", "method": "", "timeline": "", "successSignal": ""}, "scores": {"clarity": 6, "pain": 6, "differentiation": 6, "buildability": 6, "distribution": 6, "monetization": 6, "evidence": 4}, "nextStep": "Done"}\n\nThis analysis was generated by IdeaGauntlet.';
  }
}

/**
 * Provider that returns a JSON with verbose text before the actual JSON.
 */
class PrefixedTextProvider implements LLMProvider {
  kind = "custom" as const;
  async complete(): Promise<string> {
    return "Here is my analysis:\n\n{\"oneLineVerdict\": \"Prefixed test\", \"topRisks\": [], \"topAssumptions\": [], \"bestCase\": \"\", \"worstCase\": \"\", \"distributionRisk\": \"\", \"monetizationRisk\": \"\", \"buildabilityRisk\": \"\", \"fastestValidationTest\": {\"description\": \"\", \"method\": \"\", \"timeline\": \"\", \"successSignal\": \"\"}, \"scores\": {\"clarity\": 4, \"pain\": 4, \"differentiation\": 4, \"buildability\": 4, \"distribution\": 4, \"monetization\": 4, \"evidence\": 2}, \"nextStep\": \"Next\"}";
  }
}

/**
 * Provider that times out — takes 500ms, but caller sets 50ms timeout.
 */
class SlowProvider implements LLMProvider {
  kind = "custom" as const;
  async complete(prompt: string, options?: CompletionOptions): Promise<string> {
    return new Promise((resolve, reject) => {
      const timer = setTimeout(() => {
        resolve('{"oneLineVerdict": "Late response"}');
      }, 500);
      options?.signal?.addEventListener("abort", () => {
        clearTimeout(timer);
        reject(new DOMException("Aborted", "AbortError"));
      });
    });
  }
}

const testIdea = { idea: "A test idea for error paths", mode: "quick" as const };

describe("jsonRepair", () => {
  it("strips markdown fences", () => {
    const fenced = "```json\n{\"key\": \"value\"}\n```";
    expect(stripMarkdownFences(fenced)).toBe('{"key": "value"}');
  });

  it("strips fences without language tag", () => {
    const fenced = "```\n{\"key\": \"value\"}\n```";
    expect(stripMarkdownFences(fenced)).toBe('{"key": "value"}');
  });

  it("extracts JSON from trailing text", () => {
    const result = extractJSON('{"key": "value"}\n\nSome trailing text.');
    expect(result).toEqual({ key: "value" });
  });

  it("extracts JSON from prefixed text", () => {
    const result = extractJSON('Here is the data:\n{"key": "value"}');
    expect(result).toEqual({ key: "value" });
  });

  it("returns null for no JSON", () => {
    const result = extractJSON("This is just text, no JSON here.");
    expect(result).toBeNull();
  });

  it("handles nested braces in strings", () => {
    const result = extractJSON('{"text": "has } in it", "key": 1}');
    expect(result).toEqual({ text: "has } in it", key: 1 });
  });

  it("handles arrays", () => {
    const result = extractJSON('[{"a": 1}, {"b": 2}]');
    expect(result).toEqual([{ a: 1 }, { b: 2 }]);
  });

  it("returns null for empty input", () => {
    expect(extractJSON("")).toBeNull();
  });
});

describe("Engine error paths", () => {
  it("immuneEngine handles provider error gracefully", async () => {
    const provider = new ErrorProvider();
    const report = await runImmuneEngine(testIdea, provider, { enableSearch: false });
    expect(report.mode).toBe("quick");
    expect(report.id).toBeTruthy();
  });

  it("immuneEngine handles empty response", async () => {
    const provider = new EmptyProvider();
    const report = await runImmuneEngine(testIdea, provider, { enableSearch: false });
    expect(report.mode).toBe("quick");
    expect(report.id).toBeTruthy();
  });

  it("immuneEngine handles malformed JSON (prose only)", async () => {
    const provider = new MalformedProvider();
    const report = await runImmuneEngine(testIdea, provider, { enableSearch: false });
    expect(report.mode).toBe("quick");
    expect(Array.isArray(report.risks)).toBe(true);
  });

  it("immuneEngine extracts JSON from fenced markdown", async () => {
    const provider = new FencedJsonProvider();
    const report = await runImmuneEngine(testIdea, provider, { enableSearch: false });
    expect(report.mode).toBe("quick");
    expect(report.quickReport).toBeTruthy();
    expect(report.quickReport!.oneLineVerdict).toBe("Test verdict");
  });

  it("immuneEngine extracts JSON with trailing text", async () => {
    const provider = new TrailingTextProvider();
    const report = await runImmuneEngine(testIdea, provider, { enableSearch: false });
    expect(report.mode).toBe("quick");
    expect(report.quickReport!.oneLineVerdict).toBe("Trailing text test");
  });

  it("immuneEngine extracts JSON with prefixed text", async () => {
    const provider = new PrefixedTextProvider();
    const report = await runImmuneEngine(testIdea, provider, { enableSearch: false });
    expect(report.mode).toBe("quick");
    expect(report.quickReport!.oneLineVerdict).toBe("Prefixed test");
  });

  it("courtEngine handles provider error gracefully", async () => {
    const provider = new ErrorProvider();
    const report = await runCourtEngine(testIdea, provider, { enableSearch: false });
    expect(report.mode).toBe("court");
    expect(report.courtDebate).toBeTruthy();
  });

  it("courtEngine handles empty response", async () => {
    const provider = new EmptyProvider();
    const report = await runCourtEngine(testIdea, provider, { enableSearch: false });
    expect(report.mode).toBe("court");
    expect(report.courtDebate).toBeTruthy();
  });

  it("mvpPlanner handles provider error gracefully", async () => {
    const provider = new ErrorProvider();
    const report = await runMvpPlanner(testIdea, provider, { enableSearch: false });
    expect(report.mode).toBe("mvp");
    expect(report.mvpPlan).toBeTruthy();
    expect(report.mvpPlan!.goal).toBeTruthy();
  });

  it("mvpPlanner handles malformed JSON", async () => {
    const provider = new MalformedProvider();
    const report = await runMvpPlanner(testIdea, provider, { enableSearch: false });
    expect(report.mode).toBe("mvp");
    expect(report.mvpPlan!.goal).toBeTruthy();
  });

  it("runUserLab handles provider error gracefully", async () => {
    const provider = new ErrorProvider();
    const report = await runUserLab(testIdea, provider, 3, { enableSearch: false });
    expect(report.mode).toBe("users");
    expect(Array.isArray(report.syntheticUsers)).toBe(true);
    expect(report.syntheticUsers!.length).toBe(0);
  });

  it("runCompareEngine handles provider error gracefully", async () => {
    const provider = new ErrorProvider();
    const ideas = [
      { idea: "Idea 1", mode: "compare" as const },
      { idea: "Idea 2", mode: "compare" as const },
    ];
    const report = await runCompareEngine(ideas, provider, { enableSearch: false });
    expect(report.mode).toBe("compare");
    expect(report.comparison).toBeTruthy();
  });

  it("provider timeout triggers AbortError", async () => {
    const provider = new SlowProvider();
    const ctrl = new AbortController();
    setTimeout(() => ctrl.abort(), 50);
    await expect(
      provider.complete("test", { signal: ctrl.signal }),
    ).rejects.toThrow();
  });
});
