import type { GauntletReport, Risk, Assumption, KillTest, SyntheticPersona, Scorecard, CourtSession, MVPPlan, ComparisonResult, ComparedIdea } from "./types.js";
import { medianScore } from "./scoring.js";

export function buildReport(report: GauntletReport): string {
  const lines: string[] = [];

  lines.push("# IdeaGauntlet Report\n");

  if (report.mode === "quick") {
    lines.push(`**Generated:** ${report.createdAt}`);
    lines.push(`**Mode:** ${report.mode}`);
    lines.push(`**Idea:** ${report.input.idea}\n`);
  }

  lines.push(`## Verdict\n\n${report.verdict}\n`);

  if (report.coreInsight) { lines.push(`## Core Insight\n\n${report.coreInsight}\n`); }
  if (report.strongestCase) { lines.push(`## Strongest Case\n\n${report.strongestCase}\n`); }
  if (report.weakestAssumption) { lines.push(`## Weakest Assumption\n\n${report.weakestAssumption}\n`); }
  if (report.scores) { lines.push(`## Scorecard\n\n${buildScorecardTable(report.scores)}\n`); }
  if (report.risks && report.risks.length > 0) { lines.push(`## Top Failure Modes\n\n${buildRiskList(report.risks)}\n`); }
  if (report.assumptions && report.assumptions.length > 0) { lines.push(`## Dangerous Assumptions\n\n${buildAssumptionList(report.assumptions)}\n`); }
  if (report.killTests && report.killTests.length > 0) { lines.push(`## Kill Tests\n\n${buildKillTestList(report.killTests)}\n`); }
  if (report.syntheticUsers && report.syntheticUsers.length > 0) {
    lines.push(`## Synthetic Users\n\n${buildSyntheticUserList(report.syntheticUsers)}\n`);
    lines.push("> **Disclaimer:** Synthetic users are fictional archetypes generated by AI. They are not a substitute for real user interviews. Use them to prepare for real research, not to replace it.\n");
  }
  if (report.court) {
    lines.push(`## Court Debate\n\n${buildCourtSession(report.court)}\n`);
  }
  if (report.mvpPlan) {
    lines.push(`## MVP Validation Plan\n\n${buildMvpPlan(report.mvpPlan)}\n`);
  }
  if (report.comparison) {
    lines.push(`## Idea Comparison\n\n${buildComparison(report.comparison)}\n`);
  }
  if (report.nextActions && report.nextActions.length > 0) { lines.push(`## Next Actions\n\n${buildActionList(report.nextActions)}\n`); }

  lines.push("---\n");
  lines.push("*Report generated by IdeaGauntlet. Scores are diagnostic signals, not predictions. Synthetic analysis is not a substitute for real user research.*\n");
  return lines.join("\n");
}

function buildScorecardTable(scores: Scorecard): string {
  const rows = ["| Dimension | Score |", "|-----------|-------|"];
  const labels: Record<keyof Scorecard, string> = {
    clarity: "Clarity", pain: "Pain", differentiation: "Differentiation",
    buildability: "Buildability", distribution: "Distribution",
    monetization: "Monetization", evidence: "Evidence",
  };
  for (const [key, label] of Object.entries(labels)) {
    const val = scores[key as keyof Scorecard];
    rows.push(`| ${label} | ${val}/10 |`);
  }
  rows.push(`| **Overall** | **${medianScore(scores)}/10** |`);
  return rows.join("\n");
}

function buildRiskList(risks: Risk[]): string {
  return risks.map((r, i) =>
    `${i + 1}. **${r.title}** (${r.severity}) — ${r.explanation}${r.mitigation ? `\n   - Mitigation: ${r.mitigation}` : ""}`
  ).join("\n");
}

function buildAssumptionList(assumptions: Assumption[]): string {
  return assumptions.map((a, i) =>
    `${i + 1}. **${a.title}** (confidence: ${a.confidence})\n   - Why it matters: ${a.whyItMatters}\n   - How to test: ${a.howToTest}`
  ).join("\n\n");
}

function buildKillTestList(tests: KillTest[]): string {
  return tests.map((t) =>
    `### ${t.title}\n- **Method:** ${t.method}\n- **Timeframe:** ${t.timeframe}\n- **Success signal:** ${t.successSignal}\n- **Kill signal:** ${t.killSignal}`
  ).join("\n\n");
}

function buildSyntheticUserList(users: SyntheticPersona[]): string {
  return users.map((u) =>
    `### ${u.name} (${u.archetype})\n- **Goal:** ${u.goal}\n- **Current workaround:** ${u.currentWorkaround}\n- **Trigger to try:** ${u.triggerToTry}\n- **Primary objection:** ${u.primaryObjection}\n- **Willingness to pay:** ${u.willingnessToPay}\n- **Likely churn reason:** ${u.likelyChurnReason}\n- **Quote:** "${u.quote}"\n- **Interview question:** ${u.interviewQuestion}`
  ).join("\n\n");
}

function buildCourtSession(court: CourtSession): string {
  const turns = court.transcript
    .map((t) => `### ${t.role}\n\n${t.argument}`)
    .join("\n\n");
  return `${turns}\n\n**Verdict:** ${court.verdict}\n\n**Unresolved Questions:**\n${court.unresolvedQuestions.map((q) => `- ${q}`).join("\n")}`;
}

function buildActionList(actions: string[]): string {
  return actions.map((a, i) => `${i + 1}. ${a}`).join("\n");
}

function buildMvpPlan(plan: MVPPlan): string {
  const parts: string[] = [];
  parts.push(`**Goal:** ${plan.goal}\n`);
  parts.push(`**Timeline:** ${plan.timeline}\n`);
  parts.push("**Scope:**\n" + plan.scope.map((s, i) => `${i + 1}. ${s}`).join("\n"));
  parts.push("**Non-goals:**\n" + plan.nonGoals.map((s, i) => `${i + 1}. ${s}`).join("\n"));
  parts.push("**Metrics:**\n" + plan.metrics.map((s, i) => `${i + 1}. ${s}`).join("\n"));
  return parts.join("\n");
}

function buildComparison(comparison: ComparisonResult): string {
  const parts: string[] = [];
  parts.push(`**Recommended pick:** ${comparison.recommendedPick}\n`);
  parts.push(`**Fastest to validate:** ${comparison.fastestToValidate}\n`);
  parts.push(`**Highest upside:** ${comparison.highestUpside}\n`);
  parts.push("### Ranking\n");
  parts.push(comparison.ranking.map((r, i) => `${i + 1}. ${r}`).join("\n"));
  parts.push("\n### Detailed Scores\n");
  parts.push("| Idea | Verdict | Score | Riskiest Assumption | Evidence |");
  parts.push("|------|---------|-------|---------------------|----------|");
  for (const idea of comparison.ideas) {
    parts.push(`| ${idea.title} | ${idea.verdict} | ${idea.score}/10 | ${idea.riskiestAssumption} | ${idea.evidenceScore}/10 |`);
  }
  return parts.join("\n");
}
