import type { GauntletReport, Risk, Assumption, KillTest, SyntheticPersona, Scorecard, ScoreRubricEntry, CourtSession, MVPPlan, ComparisonResult, ComparedIdea } from "./types.js";
import type { EnhancedCourtDebate, EnhancedQuickReport, EnhancedPersona, UserSynthesis, EnhancedMVPPlan, EnhancedComparisonResult } from "./types.js";
import type { CompetitorLandscape, NicheOpportunity } from "../search/types.js";
import { overallScore } from "./scoring.js";

export function buildReport(report: GauntletReport): string {
  const lines: string[] = [];

  lines.push("# IdeaGauntlet Report\n");

  if (report.mode === "quick") {
    lines.push(`**Generated:** ${report.createdAt}`);
    lines.push(`**Mode:** ${report.mode}`);
    lines.push(`**Idea:** ${report.input.idea}\n`);
  }

  lines.push(`## Verdict\n\n${report.verdict}\n`);

  if (report.brutalTakeaway) { lines.push(`> 🔪 **${report.brutalTakeaway}**\n`); }
  if (report.coreInsight) { lines.push(`## Core Insight\n\n${report.coreInsight}\n`); }
  if (report.strongestCase) { lines.push(`## Strongest Case\n\n${report.strongestCase}\n`); }
  if (report.weakestAssumption) { lines.push(`## Weakest Assumption\n\n${report.weakestAssumption}\n`); }
  if (report.scores) { lines.push(`## Scorecard\n\n${buildScorecardTable(report.scores, report.scoreRubric, report.unassessedDimensions)}\n`); }
  if (report.risks && report.risks.length > 0) { lines.push(`## Top Failure Modes\n\n${buildRiskList(report.risks)}\n`); }
  if (report.assumptions && report.assumptions.length > 0) { lines.push(`## Dangerous Assumptions\n\n${buildAssumptionList(report.assumptions)}\n`); }
  if (report.killTests && report.killTests.length > 0) { lines.push(`## Kill Tests\n\n${buildKillTestList(report.killTests)}\n`); }
  if (report.syntheticUsers && report.syntheticUsers.length > 0) {
    lines.push(`## Synthetic Users\n\n${buildSyntheticUserList(report.syntheticUsers)}\n`);
    lines.push("> **Disclaimer:** Synthetic users are fictional archetypes generated by AI. They are not a substitute for real user interviews. Use them to prepare for real research, not to replace it.\n");
  }
  if (report.court) {
    lines.push(`## Court Debate\n\n${buildCourtSession(report.court)}\n`);
  }
  if (report.mvpPlan) {
    lines.push(`## MVP Validation Plan\n\n${buildMvpPlan(report.mvpPlan)}\n`);
  }
  if (report.comparison) {
    lines.push(`## Idea Comparison\n\n${buildComparison(report.comparison)}\n`);
  }
  if (report.courtDebate) {
    lines.push(`## Court Debate Report\n\n${buildEnhancedCourtDebate(report.courtDebate)}\n`);
  }
  if (report.quickReport) {
    lines.push(`## Quick Critique\n\n${buildEnhancedQuickReport(report.quickReport)}\n`);
  }
  if (report.enhancedSyntheticUsers && report.enhancedSyntheticUsers.length > 0) {
    lines.push(`## Enhanced Synthetic Users\n\n${buildEnhancedPersonaList(report.enhancedSyntheticUsers)}\n`);
    lines.push("> **Disclaimer:** Synthetic users are fictional archetypes generated by AI. They are not a substitute for real user interviews. Use them to prepare for real research, not to replace it.\n");
  }
  if (report.userSynthesis) {
    lines.push(`## User Synthesis\n\n${buildUserSynthesis(report.userSynthesis)}\n`);
  }
  if (report.enhancedMvpPlan) {
    lines.push(`## Enhanced MVP Plan\n\n${buildEnhancedMvpPlan(report.enhancedMvpPlan)}\n`);
  }
  if (report.enhancedComparison) {
    lines.push(`## Enhanced Comparison\n\n${buildEnhancedComparison(report.enhancedComparison)}\n`);
  }
  if (report.nextActions && report.nextActions.length > 0) { lines.push(`## Next Actions\n\n${buildActionList(report.nextActions)}\n`); }

  lines.push("---\n");
  lines.push("*Report generated by IdeaGauntlet. Scores are diagnostic signals, not predictions. Synthetic analysis is not a substitute for real user research.*\n");
  return lines.join("\n");
}

function buildScorecardTable(
  scores: Scorecard,
  rubric?: Partial<Record<keyof Scorecard, ScoreRubricEntry>>,
  unassessed?: (keyof Scorecard)[],
): string {
  const labels: Record<keyof Scorecard, string> = {
    clarity: "Clarity", pain: "Pain", differentiation: "Differentiation",
    buildability: "Buildability", distribution: "Distribution",
    monetization: "Monetization", evidence: "Evidence",
  };
  const skip = new Set(unassessed ?? []);
  const cell = (s?: string) => (s ?? "").replace(/\|/g, "\\|").replace(/\n+/g, " ");
  const hasRubric = rubric && Object.keys(rubric).length > 0;
  const rows = hasRubric
    ? ["| Dimension | Score | Evidence | What would move it |", "|---|---|---|---|"]
    : ["| Dimension | Score |", "|-----------|-------|"];
  for (const [key, label] of Object.entries(labels)) {
    const dim = key as keyof Scorecard;
    if (skip.has(dim)) {
      rows.push(hasRubric
        ? `| ${label} | — | _not assessed in this mode_ | |`
        : `| ${label} | — |`);
      continue;
    }
    const val = `${scores[dim]}/10`;
    if (hasRubric) {
      const entry = rubric[dim];
      rows.push(`| ${label} | ${val} | ${cell(entry?.evidence)} | ${cell(entry?.sensitivity)} |`);
    } else {
      rows.push(`| ${label} | ${val} |`);
    }
  }
  const overall = overallScore(scores, unassessed);
  // F-02: Confidence interval — ±2 reflects inherent LLM scoring uncertainty.
  const confLow = Math.max(1, overall - 2);
  const confHigh = Math.min(10, overall + 2);
  const overallStr = hasRubric
    ? `| **Overall** | **${overall}/10** | Median of assessed dimensions | |`
    : `| **Overall** | **${overall}/10** |`;
  rows.push(hasRubric
    ? `| **Confidence** | **${confLow}–${confHigh}/10** | ±2 reflects LLM scoring uncertainty | |`
    : `| **Confidence** | **${confLow}–${confHigh}/10** |`);
  rows.push(overallStr);
  return rows.join("\n");
}

function buildRiskList(risks: Risk[]): string {
  return risks.map((r, i) =>
    `${i + 1}. **${r.title}** (${r.severity}) — ${r.explanation}${r.mitigation ? `\n   - Mitigation: ${r.mitigation}` : ""}`
  ).join("\n");
}

function buildAssumptionList(assumptions: Assumption[]): string {
  return assumptions.map((a, i) =>
    `${i + 1}. **${a.title}** (confidence: ${a.confidence})\n   - Why it matters: ${a.whyItMatters}\n   - How to test: ${a.howToTest}`
  ).join("\n\n");
}

function buildKillTestList(tests: KillTest[]): string {
  return tests.map((t) =>
    `### ${t.title}\n- **Method:** ${t.method}\n- **Timeframe:** ${t.timeframe}\n- **Success signal:** ${t.successSignal}\n- **Kill signal:** ${t.killSignal}`
  ).join("\n\n");
}

function buildSyntheticUserList(users: SyntheticPersona[]): string {
  return users.map((u) =>
    `### ${u.name} (${u.archetype})\n- **Goal:** ${u.goal}\n- **Current workaround:** ${u.currentWorkaround}\n- **Trigger to try:** ${u.triggerToTry}\n- **Primary objection:** ${u.primaryObjection}\n- **Willingness to pay:** ${u.willingnessToPay}\n- **Likely churn reason:** ${u.likelyChurnReason}\n- **Quote:** "${u.quote}"\n- **Interview question:** ${u.interviewQuestion}`
  ).join("\n\n");
}

function buildCourtSession(court: CourtSession): string {
  const turns = court.transcript
    .map((t) => `### ${t.role}\n\n${t.argument}`)
    .join("\n\n");
  return `${turns}\n\n**Verdict:** ${court.verdict}\n\n**Unresolved Questions:**\n${court.unresolvedQuestions.map((q) => `- ${q}`).join("\n")}`;
}

function buildActionList(actions: string[]): string {
  return actions.map((a, i) => `${i + 1}. ${a}`).join("\n");
}

function buildMvpPlan(plan: MVPPlan): string {
  const parts: string[] = [];
  parts.push(`**Goal:** ${plan.goal}\n`);
  parts.push(`**Timeline:** ${plan.timeline}\n`);
  parts.push("**Scope:**\n" + plan.scope.map((s, i) => `${i + 1}. ${s}`).join("\n"));
  parts.push("**Non-goals:**\n" + plan.nonGoals.map((s, i) => `${i + 1}. ${s}`).join("\n"));
  parts.push("**Metrics:**\n" + plan.metrics.map((s, i) => `${i + 1}. ${s}`).join("\n"));
  return parts.join("\n");
}

function buildComparison(comparison: ComparisonResult): string {
  const parts: string[] = [];
  parts.push(`**Recommended pick:** ${comparison.recommendedPick}\n`);
  parts.push(`**Fastest to validate:** ${comparison.fastestToValidate}\n`);
  parts.push(`**Highest upside:** ${comparison.highestUpside}\n`);
  parts.push("### Ranking\n");
  parts.push(comparison.ranking.map((r, i) => `${i + 1}. ${r}`).join("\n"));
  parts.push("\n### Detailed Scores\n");
  parts.push("| Idea | Verdict | Score | Riskiest Assumption | Evidence |");
  parts.push("|------|---------|-------|---------------------|----------|");
  for (const idea of comparison.ideas) {
    parts.push(`| ${idea.title} | ${idea.verdict} | ${idea.score}/10 | ${idea.riskiestAssumption} | ${idea.evidenceScore}/10 |`);
  }
  return parts.join("\n");
}

function buildEnhancedCourtDebate(debate: EnhancedCourtDebate): string {
  const parts: string[] = [];
  parts.push(`### Idea Snapshot\n\n- **Idea:** ${debate.ideaSnapshot.idea}\n- **Target user:** ${debate.ideaSnapshot.targetUser}\n- **Market:** ${debate.ideaSnapshot.market}\n- **Stage:** ${debate.ideaSnapshot.stage}\n- **Key promise:** ${debate.ideaSnapshot.keyPromise}`);

  if (debate.assumptionsMap.length > 0) {
    parts.push("### Assumptions Map\n");
    parts.push(debate.assumptionsMap.map((a, i) =>
      `${i + 1}. **${a.assumption}** (${a.riskLevel}) — ${a.whyItMatters}`
    ).join("\n"));
  }

  if (debate.roleArguments.length > 0) {
    parts.push("### Role Arguments\n");
    parts.push(debate.roleArguments.map((ra) =>
      `**${ra.roleName}:** ${ra.argument}`
    ).join("\n\n"));
  }

  if (debate.crossExamination) {
    parts.push(`### Cross-Examination\n\n${debate.crossExamination}`);
  }

  if (debate.evidenceAudit) {
    parts.push(`### Evidence Audit\n\n${debate.evidenceAudit}`);
  }

  if (debate.killTests.length > 0) {
    parts.push("### Kill Tests\n");
    parts.push(debate.killTests.map((kt) =>
      `**${kt.title}**\n- Method: ${kt.method}\n- Timeframe: ${kt.timeframe}\n- Success: ${kt.successSignal}\n- Kill: ${kt.killSignal}`
    ).join("\n\n"));
  }

  if (debate.scoresDetailed.length > 0) {
    parts.push("### Scores\n");
    const esc = (s?: string) => (s ?? "").replace(/\|/g, "\\|").replace(/\n+/g, " ");
    const hasSensitivity = debate.scoresDetailed.some((s) => s.sensitivity);
    const rows = hasSensitivity
      ? ["| Dimension | Score | Evidence | What would move it |", "|---|---|---|---|"]
      : ["| Dimension | Score | Reason |", "|---|---|---|"];
    for (const s of debate.scoresDetailed) {
      rows.push(hasSensitivity
        ? `| ${esc(s.dimension)} | ${s.score}/10 | ${esc(s.reason)} | ${esc(s.sensitivity)} |`
        : `| ${esc(s.dimension)} | ${s.score}/10 | ${esc(s.reason)} |`);
    }
    parts.push(rows.join("\n"));
  }

  if (debate.verdictDetail) {
    parts.push(`### Verdict\n\n${debate.verdictDetail}`);
  }

  if (debate.nextActions.length > 0) {
    parts.push("### Next Actions\n");
    parts.push(debate.nextActions.map((a, i) => `${i + 1}. ${a}`).join("\n"));
  }

  if (debate.competitorLandscape) {
    parts.push(buildCompetitorLandscape(debate.competitorLandscape));
  }

  if (debate.nicheOpportunities && debate.nicheOpportunities.length > 0) {
    parts.push(buildNicheOpportunities(debate.nicheOpportunities));
  }

  return parts.join("\n\n");
}

function buildEnhancedQuickReport(qr: EnhancedQuickReport): string {
  const parts: string[] = [];
  if (qr.oneLineVerdict) parts.push(`**Verdict:** ${qr.oneLineVerdict}`);
  if (qr.bestCase) parts.push(`**Best case:** ${qr.bestCase}`);
  if (qr.worstCase) parts.push(`**Worst case:** ${qr.worstCase}`);
  if (qr.distributionRisk) parts.push(`**Distribution risk:** ${qr.distributionRisk}`);
  if (qr.monetizationRisk) parts.push(`**Monetization risk:** ${qr.monetizationRisk}`);
  if (qr.buildabilityRisk) parts.push(`**Buildability risk:** ${qr.buildabilityRisk}`);
  if (qr.fastestValidationTest?.description) {
    parts.push(`**Fastest test:** ${qr.fastestValidationTest.description} (${qr.fastestValidationTest.method}, ${qr.fastestValidationTest.timeline})`);
  }
  if (qr.competitorAnalysis) {
    parts.push(buildCompetitorLandscape(qr.competitorAnalysis));
  }
  if (qr.nicheOpportunities && qr.nicheOpportunities.length > 0) {
    parts.push(buildNicheOpportunities(qr.nicheOpportunities));
  }
  if (qr.nextStep) parts.push(`**Next step:** ${qr.nextStep}`);
  return parts.join("\n\n");
}

function buildEnhancedPersonaList(users: EnhancedPersona[]): string {
  return users.map((u) =>
    `### ${u.name} (${u.archetype})\n` +
    `- **Segment:** ${u.segmentDescription}\n` +
    `- **Context:** ${u.context}\n` +
    `- **Current workaround:** ${u.currentWorkaround}\n` +
    `- **Trigger event:** ${u.triggerEvent}\n` +
    `- **Desired outcome:** ${u.desiredOutcome}\n` +
    `- **Primary objection:** ${u.primaryObjection}\n` +
    `- **Switching cost:** ${u.switchingCost}\n` +
    `- **Willingness to pay:** ${u.willingnessToPay}\n` +
    `- **Adoption blocker:** ${u.adoptionBlocker}\n` +
    `- **Likely churn reason:** ${u.likelyChurnReason}\n` +
    `- **Quote:** "${u.quote}"\n` +
    `- **Interview question:** ${u.interviewQuestion}`
  ).join("\n\n");
}

function buildUserSynthesis(s: UserSynthesis): string {
  const parts: string[] = [];
  if (s.recurringObjections.length > 0) {
    parts.push("**Recurring objections:**\n" + s.recurringObjections.map((o) => `- ${o}`).join("\n"));
  }
  if (s.surprisingSegments.length > 0) {
    parts.push("**Surprising segments:**\n" + s.surprisingSegments.map((sg) => `- ${sg}`).join("\n"));
  }
  if (s.segmentsLikelyToCare.length > 0) {
    parts.push("**Segments likely to care:**\n" + s.segmentsLikelyToCare.map((sg) => `- ${sg}`).join("\n"));
  }
  if (s.segmentsUnlikelyToCare.length > 0) {
    parts.push("**Segments unlikely to care:**\n" + s.segmentsUnlikelyToCare.map((sg) => `- ${sg}`).join("\n"));
  }
  if (s.interviewQuestions.length > 0) {
    parts.push("**Interview questions:**\n" + s.interviewQuestions.map((q, i) => `${i + 1}. ${q}`).join("\n"));
  }
  if (s.fakeDoorTestIdeas.length > 0) {
    parts.push("**Fake-door test ideas:**\n" + s.fakeDoorTestIdeas.map((f, i) => `${i + 1}. ${f}`).join("\n"));
  }
  return parts.join("\n\n");
}

function buildEnhancedMvpPlan(p: EnhancedMVPPlan): string {
  const parts: string[] = [];
  if (p.coreHypothesis) parts.push(`**Core hypothesis:** ${p.coreHypothesis}`);
  if (p.mvpWedge) parts.push(`**MVP wedge:** ${p.mvpWedge}`);
  if (p.validationPlan.length > 0) {
    parts.push("**Validation plan:**\n" + p.validationPlan.map((s, i) => `${i + 1}. ${s}`).join("\n"));
  }
  if (p.killCriteria.length > 0) {
    parts.push("**Kill criteria:**\n" + p.killCriteria.map((k, i) => `${i + 1}. ${k}`).join("\n"));
  }
  if (p.pivotOptions.length > 0) {
    parts.push("**Pivot options:**\n" + p.pivotOptions.map((po, i) => `${i + 1}. ${po}`).join("\n"));
  }
  if (p.competitiveWedge) parts.push(`**Competitive wedge:** ${p.competitiveWedge}`);
  if (p.nicheStrategy) {
    parts.push(`**Niche strategy:** ${p.nicheStrategy.niche}\n- **Why underserved:** ${p.nicheStrategy.whyUnderserved}\n- **How to reach:** ${p.nicheStrategy.howToReach}`);
  }
  if (p.recommendedScope) parts.push(`**Recommended scope:** ${p.recommendedScope}`);
  return parts.join("\n\n");
}

function buildEnhancedComparison(c: EnhancedComparisonResult): string {
  const parts: string[] = [];

  if (c.comparisonMatrix.length > 0) {
    const criteria = Object.keys(c.comparisonMatrix[0].criteria ?? {});
    const header = `| Idea | ${criteria.map((k) => k.charAt(0).toUpperCase() + k.slice(1)).join(" | ")} |`;
    const sep = `|${criteria.map(() => "---|").join("")}`;
    const rows = c.comparisonMatrix.map((row) => {
      const vals = criteria.map((k) => (row.criteria[k] ?? "-").toString());
      return `| ${row.ideaTitle} | ${vals.join(" | ")} |`;
    });
    parts.push(`### Comparison Matrix\n\n${[header, sep, ...rows].join("\n")}`);
  }

  if (c.recommendation.pick) {
    parts.push(`**Recommendation:** ${c.recommendation.pick}`);
    if (c.recommendation.caveats.length > 0) {
      parts.push("**Caveats:**\n" + c.recommendation.caveats.map((cv) => `- ${cv}`).join("\n"));
    }
  }

  if (c.competitorLandscapePerIdea && c.competitorLandscapePerIdea.length > 0) {
    parts.push("### Competitor Landscape Per Idea\n");
    for (const item of c.competitorLandscapePerIdea) {
      parts.push(`**${item.ideaTitle}:**\n` + buildCompetitorLandscape(item.landscape));
    }
  }

  if (c.nicheOpportunitiesPerIdea && c.nicheOpportunitiesPerIdea.length > 0) {
    parts.push("### Niche Opportunities Per Idea\n");
    for (const item of c.nicheOpportunitiesPerIdea) {
      if (item.niches.length > 0) {
        parts.push(`**${item.ideaTitle}:**\n` + buildNicheOpportunities(item.niches));
      }
    }
  }

  return parts.join("\n\n");
}

// ─── Competitor + niche rendering helpers ──────────────────────

function buildCompetitorLandscape(landscape: CompetitorLandscape): string {
  const parts: string[] = [`### Competitor Landscape\n\n**Saturation:** ${landscape.saturationLevel} (${landscape.competitors.length} competitors)\n\n${landscape.analysisNote}`];
  if (landscape.competitors.length > 0) {
    parts.push("\n| # | Competitor | Type | Pricing | Features | Weaknesses |\n|---|---|---|---|---|---|");
    landscape.competitors.forEach((c, i) => {
      const features = c.features?.join("; ") ?? "-";
      const weaknesses = c.weaknesses?.join("; ") ?? "-";
      parts.push(`| ${i + 1} | [${c.name}](${c.url}) | ${c.type} | ${c.pricing ?? "-"} | ${features} | ${weaknesses} |`);
    });
  }
  return parts.join("\n");
}

function buildNicheOpportunities(niches: NicheOpportunity[]): string {
  const parts: string[] = ["### Niche Opportunities\n"];
  niches.forEach((n, i) => {
    parts.push(`${i + 1}. **[${n.type}]** ${n.description}\n   - **Evidence:** ${n.evidence}\n   - **Wedge:** ${n.wedgeIdea}\n   - **Why now:** ${n.whyNow}`);
  });
  return parts.join("\n\n");
}
